steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_FULL_IMAGE_PATH}',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_FULL_IMAGE_PATH}' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run',
      'deploy', '${_BACKEND_CLOUD_RUN_SERVICE_NAME}',
      '--image', '${_FULL_IMAGE_PATH}',
      '--region', '${_IMAGE_REGION}',
      '--allow-unauthenticated'
    ]
images:
  - '${_FULL_IMAGE_PATH}'
substitutions:
  _FULL_IMAGE_PATH: ${_IMAGE_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_NAME}/${_IMAGE_NAME}
  _ARTIFACT_REGISTRY_NAME: lendo
  _IMAGE_NAME: backend
  _IMAGE_REGION: europe-west1
  _BACKEND_CLOUD_RUN_SERVICE_NAME: lendo-backend-api
options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY